### ISSUE TITLE
Didn't handle this event callback - Enhancement

### ISSUE THREAD

**Issue by shivasurya** [MohammadAbbasKhan/Example-Deep-Linking-and-Google-app-autocompletions-using-App-Indexing-API#1]
handle from pending result status ! join with us @MohammadAbbasKhan  https://github.com/shivasurya/app-indexing

result.setResultCallback(new ResultCallback<Status>() {
                @Override 
                public void onResult(Status status) {
                    if (status.isSuccess()) {
                        Log.d("success", "App Indexing API: Recorded recipeview end successfully.");
                    } else { 
                        Log.e("error", "App Indexing API: There was an error"
                                + status.toString());
                    } 
                } 
            });

**Comment by MohammadAbbasKhan** [comment]
nice work
